### ISSUE TITLE
Help needed: Download is not working

### ISSUE THREAD

**Issue by xcojonny** [podify-org/podify#62]
Hello,
thanks for this nice app! 
Unfortunately I'm not able to resolve my issue. So let me describe it:

I'm having two servers. I've been running podify on Server 1 (Ubuntu Server 22, docker) for a while now. "Out of now" it stopped working. Whenever I want to add a video it is appended to the queue: 
![Bildschirmfoto 2023-06-06 um 08 56 47](https://github.com/podify-org/podify/assets/22481238/58a4309a-bc71-4542-9c76-45da097917a2)

What I've tried so far:

1. Delete everything on Server 1 regarding podify (folders and volumes). And restarting the Server 1. Here comes the weird thing (At least to me): When I now add new videos, the queue counter is increased by one, but it has the old value in memory (so it would be 11th in queue). How is that possible?

2. To check, whether I'm doing something wrong I used my server 2 (proxmoxx, ubuntu server minimal 22, docker) to counter check my work. Here is everything working pretty fine and podify is able to download videos. (using my second server is not an option)

Anyone having a clue what I'm doing wrong? Really love to use the app!

Here's my docker-compose:
```
version: '3.4'

x-app-defaults: &app-defaults
  restart: always
  environment: &app-env
    URL_HOST: https://${HOST:?HOST not set}
    DATABASE_URL: postgres://podify:${DB_PW:?DB_PW not set}@db/podify
    REDIS_URL: redis://redis
    SECRET_KEY_BASE: ${SECRET:?SECRET not set}
    STORAGE_DIR: /storage
    INITIAL_USER_EMAIL: xx
    INITIAL_USER_PASSWORD: xx
    ENABLE_SIGNUP: "no"
  volumes:
    - storage:/storage

  depends_on:
    - db
    - redis

services:
  web:
    <<: *app-defaults
    image: maxhollmann/podify:latest
    command: start-server
    ports:
      - 3000:3000
    environment:
      <<: *app-env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.podify-secure.entrypoints=websecure"
      - "traefik.http.routers.podify-secure.rule=Host(`${HOST:?HOST not set}`)"  
      - "traefik.http.routers.podify-secure.tls=true"
      - "traefik.http.routers.podify-secure.service=podify"
      - "traefik.http.services.podify.loadbalancer.server.port=${PORT:?PORT not set}"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.podify-secure.middlewares=secHeaders@file"

    networks:
     - proxy
     - default


  worker:
    <<: *app-defaults
    image: maxhollmann/podify:latest
    command: start-worker
    environment:
      <<: *app-env

  db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: podify
      POSTGRES_PASSWORD: ${DB_PW:?DB_PW not set}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - default

  redis:
    image: redis:6
    restart: always
    networks:
    - default

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /opt/containers/podify/db/
      o: bind
  storage:
    driver: local
    driver_opts:
      type: none
      device: /opt/containers/podify/data/
      o: bind
networks:
  proxy:
    external: true
```
